kind: pipeline
name: default
steps:
  - name: notify
    image: plugins/slack
    settings:
      webhook: ${slack_hook}
      channel: logs
      username: webhookbot
  - name: test
    image: golang:1.10-alpine
    commands:
      - "go test"
  - name: build
    image: golang:1.10-alpine
    commands:
      - "go build -o ./myapp"
  - name: publish
    image: plugins/docker
    settings:
      repo: wagnerdevel/setrem-cicd
      tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: delivery
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: k8s_server
      kubernetes_cert:
        from_secret: k8s_cert
      kubernetes_token:
        from_secret: k8s_token
    commands:
      - kubectl apply -f deployment.yml
